version: "3"
services:


  bot:
    build:
      dockerfile: Dockerfile
      context: .
    command: python bot/main.py
    environment:
      - DEBUG=false
      - SECRET_KEY=${SECRET_KEY}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    container_name: devyatki_bot

    ports:
      - "8816:8816"
