version: "3.7"
services:

  bot:
    build:
      dockerfile: Dockerfile
      context: .
    image: nitrok/devyatki
    command: make docker-run-bot
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_999_CHANNEL_ID=${TELEGRAM_999_CHANNEL_ID}
      - VK_GROUP_ID=${VK_GROUP_ID}
      - VK_GROUP_ALBUM_ID=${VK_GROUP_ALBUM_ID}
      - VK_TOKEN=${VK_TOKEN}
    container_name: devyatki_bot
    ports:
      - "8816:8816"
    volumes:
      - type: bind
        source: /srv/devyatki/storage
        target: /var/lib/django-db
